title: Frieve - Audio Review
description: Beyond Story, Beyond Brand. The Truth in Silence.
url: "https://audioreview.frieve.com"
baseurl: ""
logo: /assets/images/og-image.png

# Multi-language settings
languages: ["en", "ja"]
default_lang: "en"

collections:
  companies:
    output: true
  products:
    output: true

defaults:
  - scope:
      path: ""
      type: "companies"
    values:
      layout: "company"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - dev
  - sessions
  - tools
  - lambda
