service: ogp-generator

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  memorySize: 1024
  timeout: 30
  environment:
    NODE_ENV: production

functions:
  generateOgp:
    handler: index.handler
    events:
      - http:
          path: /ogp
          method: post
          cors: true
      - http:
          path: /ogp
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                n: true
                t: false
                r: true
                l: false

package:
  patterns:
    - '!node_modules/**'
    - 'node_modules/canvas/**'
    - 'fonts/**'
    - '!test.js'
    - '!*.test.js' 